#
# docker build -t kafka -f Dockerfile-kafka .
#
FROM java-base:latest

EXPOSE 9092

# ENV
ENV KAFKA_VERSION=kafka_2.12-2.3.0

WORKDIR /kafka
ADD ./pkg/${KAFKA_VERSION}.tgz .

# ENV
ENV KAFKA_HOME=/kafka/${KAFKA_VERSION}

COPY server.properties.example ${KAFKA_HOME}/config/server.properties
CMD ${KAFKA_HOME}/bin/kafka-server-start.sh ${KAFKA_HOME}/config/server.properties
