# (https://docs.docker.com/compose/compose-file/#extension-fields)
version: '3.4'

services:
  zoo1:
    image: zookeeper:3.5.5
    container_name: zoo1
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    restart: always
    networks:
      - "mynet1"

  zoo2:
    image: zookeeper:3.5.5
    hostname: zoo2
    container_name: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181
    restart: always
    depends_on:
      - zoo1
    networks:
      - "mynet1"

  zoo3:
    image: zookeeper:3.5.5
    hostname: zoo3
    container_name: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
    restart: always
    depends_on:
      - zoo2
    networks:
      - "mynet1"

networks:
  mynet1:
    driver: bridge