#
# 测试：docker-compose up
#
version: "3.4"

# (https://docs.docker.com/compose/compose-file/#extension-fields)
x-logging:
  &default-logging
  driver: json-file
  options:
    max-size: '12m'
    max-file: '5'

x-deploy:
  &default-deploy
  restart_policy:
    condition: any
    delay: 10s

services:
  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - 2181:2181
    volumes: 
      - /opt/zookeeper/data:/zookeeper/data
    deploy: *default-deploy
    logging: *default-logging

  kafka1:
    image: kafka:latest
    container_name: kafka1
    hostname: kafka1
    ports:
      - 9091:9092
    volumes:
      - ./server.properties.1:/kafka/kafka_2.12-2.3.0/config/server.properties
    deploy: *default-deploy
    logging: *default-logging
    depends_on:
      - zookeeper

  # kafka2:
  #   image: kafka:latest
  #   container_name: kafka2
  #   hostname: kafka2
  #   ports:
  #     - 9092:9092
  #   volumes:
  #     - ./server.properties.2:/kafka/kafka_2.12-2.3.0/config/server.properties
  #   deploy: *default-deploy
  #   logging: *default-logging
  #   depends_on:
  #     - zookeeper

  # kafka3:
  #   image: kafka:latest
  #   container_name: kafka3
  #   ports:
  #     - 9093:9092
  #   volumes:
  #     - ./server.properties.3:/kafka/kafka_2.12-2.3.0/config/server.properties
  #   deploy: *default-deploy
  #   logging: *default-logging
  #   depends_on:
  #     - zookeeper