#
# 测试：docker-compose up --build
#
version: "3.4"

x-command:
  &zookeeper-run
  /home/zookeeper/bin/zkServer.sh start-foreground

x-volumes:
  &zookeeper-volumes
  - /opt/zookeeper/zookeeper-3.4.13:/home/zookeeper
  - ./zookeeper/conf/zoo.cfg:/home/zookeeper/conf/zoo.cfg

services:
  zookeeper:
    image: zookeeper:latest
    ports:
      - 2181:2181
    command: *zookeeper-run
    volumes: *zookeeper-volumes
#  kafka:
#    build:
#      context: .
#      dockerfile: ./kafka/Dockerfile
#    ports:
#      - 9092:9092
#    command: /home/kafka/kafka/bin/kafka-server-start.sh /home/kafka/kafka/config/server.properties
#    depends_on:
#      - zookeeper
